version: '3'

services:
  students_db: 
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: students
    ports:
      - 5432:5432
    volumes:
      - students_data:/var/lib/postgresql/data

  disciplines_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: disciplines
    ports:
      - 5433:5432
    volumes:
      - disciplines_data:/var/lib/postgresql/data

  matriculas_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: matriculas
    ports:
      - 5434:5432
    volumes:
      - matriculas_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  students_data:
  disciplines_data:
  matriculas_data:

  # api:
  #   build: ./containers
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - db