version: '3'

services:
  db: 
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testdb
    ports:
      - 5432:5432

  # api:
  #   build: ./containers
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - db